# -*- coding: utf-8 -*-
"""SMS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2wj8PBpiHwDyuqmNM_T6wjmIoFurant
"""

import pandas as pd
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

data = pd.read_csv('spam.csv', encoding='ISO-8859-1')
data.head()

data = data.dropna()
data.head()

data = data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)

data.columns = ['Label', 'Message']
data = data.drop_duplicates()
data.head()

def simple_preprocess(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    text = ' '.join(text.split())
    return text

data['Message'] = data['Message'].apply(simple_preprocess)
print(data[['Label', 'Message']].head())

label_encoder = LabelEncoder()
data['Encoded_Label'] = label_encoder.fit_transform(data['Label'])

X_train, X_test, y_train, y_test = train_test_split(
    data['Message'],
    data['Encoded_Label'],
    test_size=0.2,
    random_state=42
)

vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

nb_model = MultinomialNB()
nb_model.fit(X_train_vectorized, y_train)

y_pred = nb_model.predict(X_test_vectorized)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)

print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", report)