# -*- coding: utf-8 -*-
"""5th task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15D74xtP7CZBgEZgEFe_B5iiNjw7xxKJy
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

data = pd.read_csv('Advertising.csv')
data = data.drop('Unnamed: 0', axis=1)
x = data.drop('Sales', axis=1)
y = data['Sales']

X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, Y_train)

pred = model.predict(X_test)
print(mean_squared_error(Y_test, pred))

# Visualization: Actual vs Predicted Sales
plt.figure(figsize=(10, 6))
plt.scatter(Y_test, pred, alpha=0.7, color='blue')
plt.plot([Y_test.min(), Y_test.max()], [Y_test.min(), Y_test.max()], 'r--')  # Diagonal line
plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")
plt.title("Actual vs Predicted Sales Using Linear Regression")
plt.grid()
plt.show()

new_data = [[150, 25, 30]]  # Example new data: [TV, Radio, Newspaper]
predicted_sales = model.predict(new_data)
print("Predicted Sales for unseen data:", predicted_sales[0])