# -*- coding: utf-8 -*-
"""Iris Species Classification Using K-Nearest Neighbors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGU-c7zytPCL5RrZNm3PDBprqThr9bSO
"""

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns
import matplotlib.pyplot as plt

data = load_iris()
x, y = data.data, data.target

scaler = StandardScaler()
X = scaler.fit_transform(x)
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state = 42)

KNN = KNeighborsClassifier()
KNN.fit(X_train, Y_train)

pred = KNN.predict(X_test)
print("Accuracy: " ,accuracy_score(Y_test, pred))
print("Classification_report: ", classification_report(Y_test, pred))

import numpy as np
new_samples = np.array([
    [5.1, 3.5, 1.4, 0.2],  # Similar to Setosa
    [6.2, 3.4, 5.4, 2.3],  # Similar to Virginica
    [5.9, 3.0, 4.2, 1.5]   # Similar to Versicolor
])

new_samples_scaled = scaler.transform(new_samples)
prediction = KNN.predict(new_samples_scaled)
for i in prediction:
  print(data.target_names[i])

import pandas as pd
df = pd.DataFrame(data.data, columns=data.feature_names)
df['Species'] = data.target
df['Species'] = df['Species'].apply(lambda x: data.target_names[x])
df

sns.pairplot(df, hue='Species')
plt.title("Feature Distributions by Iris Species", y=1.02)
plt.show()